services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=ederson1996
      - DB_NAME=water_gas_measure
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ederson1996
      MYSQL_DATABASE: water_gas_measure
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
